name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run backend server test
      run: |
        cd server
        uvicorn main:app --host 0.0.0.0 --port 8000 --lifespan on --no-access-log &
        sleep 5
        curl -f http://127.0.0.1:8000 || exit 1

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Run frontend server test
      run: |
        cd client
        npm start &
        sleep 10
        curl -f http://127.0.0.1:3000 || exit 1
